import { createClient } from "npm:@supabase/supabase-js@2";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}}),SRC="chain-rpc";
const RPC:any={robinhood:"https://robinhood-rpc.publicnode.com",arc:"https://arc-rpc.publicnode.com",bsc:"https://bsc-rpc.publicnode.com"};
const CONF:any={robinhood:3,arc:3,bsc:5},LOOK:any={robinhood:50,arc:40,bsc:40},STEP:any={robinhood:200,arc:100,bsc:100},MAX:any={robinhood:1200,arc:600,bsc:600};
const NATIVE:any={robinhood:"ETH",arc:"ETH",bsc:"BNB"},TOPIC="0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef";
const QUOTES=new Set(["USDC","USDT","USDS","USDG","DAI","WETH","WBNB","WBTC"]);
const iso=()=>new Date().toISOString(),hex=(x:any)=>x?parseInt(String(x),16):0,short=(x:string)=>`${x.slice(0,6)}…${x.slice(-4)}`,slug=(x:string)=>x.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"token";
const topicAddr=(x:any)=>{const s=String(x||"").replace(/^0x/,"");return s.length>=40?`0x${s.slice(-40)}`.toLowerCase():""};
function response(x:any,s=200){return new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}})}
async function rpc(url:string,m:string,p:any[]){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method:m,params:p})});if(!r.ok)throw new Error(`${m} HTTP ${r.status}`);const j=await r.json();if(j?.error)throw new Error(`${m}: ${j.error.message||j.error.code}`);return j.result}
async function batch(url:string,calls:any[]){const q=calls.map((c,i)=>({jsonrpc:"2.0",id:i+1,method:c.m,params:c.p}));const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(q)});if(!r.ok)throw new Error(`batch HTTP ${r.status}`);const j=await r.json();if(!Array.isArray(j))throw new Error("invalid batch response");const map=new Map(j.map((x:any)=>[x.id,x]));return q.map(x=>map.get(x.id))}
function decodeSym(v:string){if(!v||v==="0x")return null;try{const r=v.slice(2);let z="";if(r.length===64)z=r;else if(r.length>=128){const n=parseInt(r.slice(64,128),16);if(!n||n>64)return null;z=r.slice(128,128+n*2)}else return null;const b=new Uint8Array((z.match(/.{2}/g)||[]).map(x=>parseInt(x,16)));const s=new TextDecoder().decode(b).replace(/\0+$/g,"").trim();return /^[\x20-\x7e]{1,32}$/.test(s)?s:null}catch{return null}}
function fmt(raw:bigint,dec:number,max=6){const neg=raw<0n,abs=neg?-raw:raw,s=abs.toString().padStart(dec+1,"0");if(!dec)return(neg?"-":"")+s;const a=s.slice(0,-dec),b=s.slice(-dec).replace(/0+$/,"").slice(0,max);return(neg?"-":"")+a+(b?"."+b:"")}
function ratio(q:string,t:string){const a=Number(q),b=Number(t);if(!Number.isFinite(a)||!Number.isFinite(b)||b===0)return null;const r=a/b;if(r>=1)return r.toFixed(4).replace(/0+$/,"").replace(/\.$/,"");if(r>=0.001)return r.toFixed(6).replace(/0+$/,"").replace(/\.$/,"");return r.toPrecision(4)}
async function getCursor(uid:string,wid:string){const {data,error}=await db.from("sync_state").select("cursor").eq("user_id",uid).eq("wallet_id",wid).eq("source",SRC).maybeSingle();if(error)throw error;try{return data?.cursor?JSON.parse(data.cursor):null}catch{return null}}
async function setState(uid:string,wid:string,v:any){const {error}=await db.from("sync_state").upsert({user_id:uid,wallet_id:wid,source:SRC,...v},{onConflict:"user_id,wallet_id,source"});if(error)throw error}
async function event(a:any){const {data,error}=await db.from("chain_events").upsert({user_id:a.uid,wallet_id:a.wid,chain:a.chain,tx_id:a.tx,event_index:a.idx,token_address:a.token,direction:a.dir,block_ref:a.block,occurred_at:a.when,raw_payload:a.raw},{onConflict:"user_id,wallet_id,chain,tx_id,event_index,token_address,direction",ignoreDuplicates:true}).select("id");if(error)throw error;return!!data?.length}
async function findOpen(uid:string,wid:string,chain:string,token:string){const {data,error}=await db.from("journal_positions").select("id").eq("user_id",uid).eq("wallet_id",wid).eq("chain",chain).eq("token_address",token).eq("status","OPEN").limit(1);if(error)throw error;return data?.[0]?.id||null}
async function position(a:any){let id=await findOpen(a.uid,a.wid,a.chain,a.token);if(!id&&a.dir==="IN"&&!QUOTES.has(a.symbol)){const {data:manual}=await db.from("journal_positions").select("id,source").eq("user_id",a.uid).eq("chain",a.chain).eq("status","OPEN").is("wallet_id",null).or(`token_address.eq.${a.token},and(token_address.is.null,symbol.ilike.${a.symbol})`).limit(2);if(manual?.length===1){id=manual[0].id;await db.from("journal_positions").update({wallet_id:a.wid,token_address:a.token,source:manual[0].source==="manual"?"manual+chain":manual[0].source,sync_source:SRC}).eq("id",id)}}
if(!id&&a.dir==="IN"&&!QUOTES.has(a.symbol)){const suffix=a.token.slice(2,10),txs=a.tx.slice(2,10);const {data,error}=await db.from("journal_positions").insert({user_id:a.uid,wallet_id:a.wid,chain:a.chain,token_address:a.token,slug:`${slug(a.symbol)}-${a.chain}-${suffix}-${txs}`,symbol:a.symbol,short_label:(a.symbol||"??").slice(0,2).toUpperCase(),status:"OPEN",opened_label:new Date(a.when).toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"UTC"}),size_label:a.sizeLabel||"Auto-detected",value_label:a.valueLabel||`${a.chain} activity`,hold_thesis_required:false,source:"chain-rpc",sync_source:SRC,first_synced_at:iso(),last_synced_at:iso(),last_activity_at:a.when}).select("id").single();if(error)throw error;id=data.id}
if(id){const patch:any={last_activity_at:a.when,last_synced_at:iso(),sync_source:SRC};if(a.sizeLabel)patch.size_label=a.sizeLabel;if(a.valueLabel)patch.value_label=a.valueLabel;await db.from("journal_positions").update(patch).eq("id",id)}return id}
async function bal(url:string,t:string,w:string){try{return BigInt(await rpc(url,"eth_call",[{to:t,data:"0x70a08231"+w.slice(2).toLowerCase().padStart(64,"0")},"latest"])||"0x0")}catch{return null}}
async function one(w:any){try{const url=RPC[w.chain],metaCache=new Map<string,any>(),meta=async(t:string)=>{if(metaCache.has(t))return metaCache.get(t);let symbol=short(t),decimals=18;try{symbol=decodeSym(await rpc(url,"eth_call",[{to:t,data:"0x95d89b41"},"latest"]))||symbol}catch{}try{decimals=hex(await rpc(url,"eth_call",[{to:t,data:"0x313ce567"},"latest"]))}catch{}const m={symbol,decimals};metaCache.set(t,m);return m};
const c=await getCursor(w.user_id,w.id),head=hex(await rpc(url,"eth_blockNumber",[])),target=Math.max(0,head-(CONF[w.chain]||3));let from=c?.block!=null?Number(c.block)+1:Math.max(0,target-(LOOK[w.chain]||40));if(from>target){await setState(w.user_id,w.id,{cursor:JSON.stringify({block:target}),status:"OK",last_success_at:iso(),last_attempt_at:iso(),error_code:null});return{ok:true,chain:w.chain,events:0}}
const to=Math.min(target,from+(MAX[w.chain]||600)-1),step=STEP[w.chain]||100;let n=0;
for(let s=from;s<=to;s+=step){const e=Math.min(to,s+step-1),calls=[];for(let b=s;b<=e;b++)calls.push({m:"eth_getBlockByNumber",p:[`0x${b.toString(16)}`,true]});const blocks=await batch(url,calls);const blockMap=new Map(blocks.filter((x:any)=>x?.result).map((x:any)=>[x.result.number,x.result]));const txs=blocks.flatMap((x:any)=>x?.result?.transactions||[]).filter((t:any)=>String(t?.from||"").toLowerCase()===w.address.toLowerCase());
for(const t of txs){const r=await rpc(url,"eth_getTransactionReceipt",[t.hash]),b=blockMap.get(r?.blockNumber),when=new Date(hex(b?.timestamp||"0x0")*1000).toISOString();const flows:any[]=[];
for(const l of r?.logs||[]){if(String(l?.topics?.[0]||"").toLowerCase()!==TOPIC||typeof l?.data!=="string"||l.data.length!==66)continue;const f=topicAddr(l.topics?.[1]),toA=topicAddr(l.topics?.[2]);let dir="";if(toA===w.address.toLowerCase())dir="IN";else if(f===w.address.toLowerCase())dir="OUT";else continue;const token=String(l.address).toLowerCase(),m=await meta(token),raw=BigInt(l.data),display=fmt(raw,m.decimals,6);flows.push({token,dir,idx:String(l.logIndex),raw,display,symbol:m.symbol,decimals:m.decimals,log:l})}
const nativeSpend=BigInt(t.value||"0x0")>0n?fmt(BigInt(t.value),18,6):"";
for(const f of flows){const fresh=await event({uid:w.user_id,wid:w.id,chain:w.chain,tx:t.hash,idx:f.idx,token:f.token,dir:f.dir,block:r.blockNumber,when,raw:{log:f.log,symbol:f.symbol,decimals:f.decimals,amount_raw:f.raw.toString(),amount_display:f.display}});if(!fresh)continue;n++;let sizeLabel="",valueLabel="";
if(f.dir==="IN"&&!QUOTES.has(f.symbol)){sizeLabel=`Bought ${f.display} ${f.symbol}`;let quote:any=null;if(nativeSpend)quote={amount:nativeSpend,symbol:NATIVE[w.chain]};if(!quote){const outs=flows.filter(x=>x.dir==="OUT"&&x.token!==f.token);const best=outs.find(x=>["USDC","USDT","USDG","DAI"].includes(x.symbol))||outs[0];if(best)quote={amount:best.display,symbol:best.symbol}}if(quote){const rr=ratio(quote.amount,f.display);valueLabel=`Spent ${quote.amount} ${quote.symbol}${rr?` · entry ${rr} ${quote.symbol}/token`:""}`}}
await position({uid:w.user_id,wid:w.id,chain:w.chain,token:f.token,symbol:f.symbol,dir:f.dir,tx:t.hash,when,sizeLabel,valueLabel})}
for(const f of flows){if(await bal(url,f.token,w.address)===0n)await db.from("journal_positions").update({status:"CLOSED",hold_thesis_required:false,last_synced_at:iso()}).eq("user_id",w.user_id).eq("wallet_id",w.id).eq("chain",w.chain).eq("token_address",f.token).eq("status","OPEN")}
}}
await setState(w.user_id,w.id,{cursor:JSON.stringify({block:to}),status:"OK",last_success_at:iso(),last_attempt_at:iso(),error_code:null,retry_after:null});await db.from("wallets").update({last_sync_status:"OK",last_sync_error:null}).eq("id",w.id);return{ok:true,wallet:w.address,chain:w.chain,events:n,from,to,head:target}}catch(e){const msg=e instanceof Error?e.message:String(e);await setState(w.user_id,w.id,{status:"ERROR",last_attempt_at:iso(),error_code:msg.slice(0,500)});await db.from("wallets").update({last_sync_status:"ERROR",last_sync_error:msg.slice(0,500)}).eq("id",w.id);return{ok:false,chain:w.chain,error:msg}}}
Deno.serve(async req=>{const {data:rt}=await db.from("sync_runtime").select("sync_key").eq("id",1).single();if(!rt||req.headers.get("x-sync-key")!==rt.sync_key)return response({error:"unauthorized"},401);const body=await req.json().catch(()=>({}));let q=db.from("wallets").select("id,user_id,chain,address,label").eq("sync_enabled",true).in("chain",["robinhood","arc","bsc"]);if(body.user_id)q=q.eq("user_id",body.user_id);if(body.chain)q=q.eq("chain",body.chain);const {data,error}=await q;if(error)return response({error:error.message},500);const results=[];for(const w of data||[])results.push(await one(w));return response({ok:true,source:SRC,results})});