import { createClient } from "npm:@supabase/supabase-js@2";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}});
const RPC:any={robinhood:"https://robinhood-rpc.publicnode.com",arc:"https://arc-rpc.publicnode.com",bsc:"https://bsc-rpc.publicnode.com",sol:"https://solana-rpc.publicnode.com"};
const STABLE=new Set(["USDC","USDT","USDG","USDS","DAI"]);
function out(x:any,s=200){return new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}})}
async function rpc(url:string,m:string,p:any[]){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method:m,params:p})});if(!r.ok)throw new Error(`${m} HTTP ${r.status}`);const j=await r.json();if(j?.error)throw new Error(j.error.message||String(j.error.code));return j.result}
function parseEntry(v:any){const m=String(v||"").match(/Spent\s+([0-9.eE+-]+)\s+([^ ·]+)(?:\s+·\s+entry\s+([0-9.eE+-]+)\s+([^/]+)\/token)?/i);if(!m)return null;const amount=Number(m[1]);return Number.isFinite(amount)?{amount,symbol:m[2],entry:Number(m[3]||0)||null}:null}
function norm(s:string){return s.toUpperCase().replace(/^W(?=SOL|ETH|BNB$)/,"")}
async function dex(token:string){try{const r=await fetch(`https://api.dexscreener.com/latest/dex/tokens/${token}`,{headers:{"accept":"application/json","user-agent":"trading-journal/1.0"}});if(!r.ok)return null;const j=await r.json(),t=token.toLowerCase();const ps=(j?.pairs||[]).filter((p:any)=>String(p?.baseToken?.address||"").toLowerCase()===t).sort((a:any,b:any)=>Number(b?.liquidity?.usd||0)-Number(a?.liquidity?.usd||0));const p=ps[0];return p?{priceUsd:Number(p.priceUsd)||null,priceNative:Number(p.priceNative)||null,quoteSymbol:String(p?.quoteToken?.symbol||"")}:null}catch{return null}}
async function evmBalance(chain:string,token:string,wallet:string){const data="0x70a08231"+wallet.slice(2).toLowerCase().padStart(64,"0");let v=String(await rpc(RPC[chain],"eth_call",[{to:token,data},"latest"])||"0x0");if(v==="0x")v="0x0";const raw=BigInt(v);let d=18;try{let dv=String(await rpc(RPC[chain],"eth_call",[{to:token,data:"0x313ce567"},"latest"])||"0x12");if(dv==="0x")dv="0x12";d=parseInt(dv,16)}catch{}return Number(raw)/10**d}
async function latestEvent(p:any){const {data}=await db.from("chain_events").select("tx_id,occurred_at,raw_payload,direction").eq("wallet_id",p.wallet_id).eq("chain",p.chain).eq("token_address",p.token_address).order("occurred_at",{ascending:false}).limit(1);return data?.[0]||null}
async function solBalance(p:any){const e=await latestEvent(p);if(!e)return null;if(e.direction==="OUT"&&String(e.raw_payload?.after??"")==="0")return 0;if(e.raw_payload?.after!=null&&e.raw_payload?.decimals!=null)return Number(e.raw_payload.after)/10**Number(e.raw_payload.decimals);const tx=await rpc(RPC.sol,"getTransaction",[e.tx_id,{encoding:"jsonParsed",commitment:"confirmed",maxSupportedTransactionVersion:0}]);if(!tx?.meta)return null;let total=0;for(const x of tx.meta.postTokenBalances||[])if(x.owner===p.wallet_address&&x.mint===p.token_address)total+=Number(x?.uiTokenAmount?.uiAmountString||0);return total}
async function findExit(p:any){const {data}=await db.from("chain_events").select("tx_id,occurred_at,raw_payload").eq("wallet_id",p.wallet_id).eq("chain",p.chain).eq("token_address",p.token_address).eq("direction","OUT").gte("occurred_at",p.created_at).order("occurred_at",{ascending:false}).limit(1);return data?.[0]||null}
function ta(x:any){return Number(x?.uiTokenAmount?.uiAmountString||0)}
async function solExit(p:any,e:any){const tx=await rpc(RPC.sol,"getTransaction",[e.tx_id,{encoding:"jsonParsed",commitment:"confirmed",maxSupportedTransactionVersion:0}]);if(!tx?.meta)return null;const pre=new Map<string,number>(),post=new Map<string,number>();for(const x of tx.meta.preTokenBalances||[])if(x.owner===p.wallet_address)pre.set(x.mint,(pre.get(x.mint)||0)+ta(x));for(const x of tx.meta.postTokenBalances||[])if(x.owner===p.wallet_address)post.set(x.mint,(post.get(x.mint)||0)+ta(x));const USDC="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",WSOL="So11111111111111111111111111111111111111112",ins:any[]=[];for(const mint of new Set([...pre.keys(),...post.keys()])){if(mint===p.token_address)continue;const d=(post.get(mint)||0)-(pre.get(mint)||0);if(d>0)ins.push({mint,amount:d})}const q=ins.find(x=>x.mint===USDC)||ins.find(x=>x.mint===WSOL);if(q)return{amount:q.amount,symbol:q.mint===USDC?"USDC":"SOL"};const keys=(tx.transaction?.message?.accountKeys||[]).map((k:any)=>typeof k==="string"?k:String(k?.pubkey||"")),i=keys.indexOf(p.wallet_address);if(i>=0){const d=(Number(tx.meta.postBalances?.[i]||0)-Number(tx.meta.preBalances?.[i]||0))/1e9;if(d>0)return{amount:d,symbol:"SOL"}}return null}
async function evmExit(p:any,e:any){const r=await rpc(RPC[p.chain],"eth_getTransactionReceipt",[e.tx_id]);if(!r)return null;const wallet=p.wallet_address.toLowerCase(),TOP="0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef";for(const l of r.logs||[]){if(String(l?.topics?.[0]||"").toLowerCase()!==TOP||String(l?.topics?.[2]||"").slice(-40).toLowerCase()!==wallet.slice(2))continue;const token=String(l.address).toLowerCase();if(token===p.token_address.toLowerCase())continue;let sym="",d=18;try{const meta=await dex(token);sym=meta?.quoteSymbol||""}catch{}try{let dv=String(await rpc(RPC[p.chain],"eth_call",[{to:token,data:"0x313ce567"},"latest"])||"0x12");if(dv==="0x")dv="0x12";d=parseInt(dv,16)}catch{}if(!sym)continue;const v=String(l.data||"0x0")==="0x"?"0x0":String(l.data||"0x0"),amount=Number(BigInt(v))/10**d;if(amount>0)return{amount,symbol:sym}}return null}
Deno.serve(async req=>{
 const {data:rt}=await db.from("sync_runtime").select("sync_key").eq("id",1).single();if(!rt||req.headers.get("x-sync-key")!==rt.sync_key)return out({error:"unauthorized"},401);
 const {data:ws}=await db.from("wallets").select("id,address");const wm=new Map((ws||[]).map((x:any)=>[x.id,x.address]));
 const cutoff=new Date(Date.now()-7*86400000).toISOString();
 const {data:ps,error}=await db.from("journal_positions").select("id,chain,status,token_address,wallet_id,created_at,size_label,value_label,total_pnl_quote").not("wallet_id","is",null).not("token_address","is",null).or(`status.eq.OPEN,and(status.eq.CLOSED,total_pnl_quote.is.null,created_at.gte.${cutoff})`).order("created_at",{ascending:false}).limit(100);if(error)return out({error:error.message},500);
 let updated=0,failed=0;const errors:any[]=[];
 for(const p0 of ps||[]){const p:any={...p0,wallet_address:wm.get(p0.wallet_id)};if(!p.wallet_address)continue;try{const holding=String(p.status)==="CLOSED"?0:(p.chain==="sol"?await solBalance(p):await evmBalance(p.chain,p.token_address,p.wallet_address));if(holding==null)continue;const market=await dex(p.token_address),entry=parseEntry(p.value_label),patch:any={current_token_balance:holding,metrics_updated_at:new Date().toISOString()};if(market?.priceUsd){patch.current_price_usd=market.priceUsd;patch.current_value_usd=holding*market.priceUsd}if(entry){patch.cost_basis_quote=entry.amount;patch.cost_basis_quote_symbol=entry.symbol}
 if(entry&&holding>0&&market){let cv:null|number=null;if(STABLE.has(entry.symbol.toUpperCase())&&market.priceUsd)cv=holding*market.priceUsd;else if(norm(entry.symbol)===norm(market.quoteSymbol)&&market.priceNative)cv=holding*market.priceNative;if(cv!=null){const pnl=cv-entry.amount,pct=entry.amount?pnl/entry.amount*100:null;Object.assign(patch,{current_value_quote:cv,unrealized_pnl_quote:pnl,total_pnl_quote:pnl,return_pct:pct,pnl_label:`${pnl>=0?"+":""}${pnl.toFixed(4)} ${entry.symbol}`,pnl_percent_label:pct==null?null:`${pct>=0?"+":""}${pct.toFixed(1)}%`})}}
 if(String(p.status)==="CLOSED"&&entry){const ex=await findExit(p);if(ex){const pr=p.chain==="sol"?await solExit(p,ex):await evmExit(p,ex);if(pr&&norm(pr.symbol)===norm(entry.symbol)){const pnl=pr.amount-entry.amount,pct=entry.amount?pnl/entry.amount*100:null;Object.assign(patch,{current_token_balance:0,current_value_quote:0,realized_pnl_quote:pnl,unrealized_pnl_quote:0,total_pnl_quote:pnl,return_pct:pct,pnl_label:`${pnl>=0?"+":""}${pnl.toFixed(4)} ${entry.symbol}`,pnl_percent_label:pct==null?null:`${pct>=0?"+":""}${pct.toFixed(1)}%`})}}}
 const {error:u}=await db.from("journal_positions").update(patch).eq("id",p.id);if(u)throw u;updated++}catch(e){failed++;errors.push({id:p.id,error:e instanceof Error?e.message:String(e)})}}
 return out({ok:true,updated,failed,errors:errors.slice(0,20)});
});