import { createClient } from "npm:@supabase/supabase-js@2";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}}),SRC="chain-rpc",RPC="https://solana-rpc.publicnode.com";
const USDC="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",WSOL="So11111111111111111111111111111111111111112";
const iso=()=>new Date().toISOString();
function response(x:any,s=200){return new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}})}
async function rpc(m:string,p:any[]){const r=await fetch(RPC,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method:m,params:p})});if(!r.ok)throw new Error(`${m} HTTP ${r.status}`);const j=await r.json();if(j?.error)throw new Error(`${m}: ${j.error.message||j.error.code}`);return j.result}
function tokInfo(x:any){try{return{amount:BigInt(x?.uiTokenAmount?.amount??"0"),decimals:Number(x?.uiTokenAmount?.decimals??0)}}catch{return{amount:0n,decimals:0}}}
function fmt(raw:bigint,dec:number,max=6){const neg=raw<0n,abs=neg?-raw:raw,s=abs.toString().padStart(dec+1,"0");if(!dec)return(neg?"-":"")+s;const a=s.slice(0,-dec),b=s.slice(-dec).replace(/0+$/,"").slice(0,max);return(neg?"-":"")+a+(b?"."+b:"")}
function num(v:string){const n=Number(v);return Number.isFinite(n)?n:null}
function ratio(q:string,t:string){const a=num(q),b=num(t);if(a==null||b==null||b===0)return null;const r=a/b;if(r>=1)return r.toFixed(4).replace(/0+$/,"").replace(/\.$/,"");if(r>=0.001)return r.toFixed(6).replace(/0+$/,"").replace(/\.$/,"");return r.toPrecision(4)}
async function getCursor(uid:string,wid:string){const {data,error}=await db.from("sync_state").select("cursor").eq("user_id",uid).eq("wallet_id",wid).eq("source",SRC).maybeSingle();if(error)throw error;try{return data?.cursor?JSON.parse(data.cursor):null}catch{return null}}
async function setState(uid:string,wid:string,v:any){const {error}=await db.from("sync_state").upsert({user_id:uid,wallet_id:wid,source:SRC,...v},{onConflict:"user_id,wallet_id,source"});if(error)throw error}
async function recordEvent(a:any){const {data,error}=await db.from("chain_events").upsert({user_id:a.uid,wallet_id:a.wid,chain:"sol",tx_id:a.tx,event_index:a.idx,token_address:a.token,direction:a.dir,block_ref:a.block,occurred_at:a.when,raw_payload:a.raw},{onConflict:"user_id,wallet_id,chain,tx_id,event_index,token_address,direction",ignoreDuplicates:true}).select("id");if(error)throw error;return!!data?.length}
async function findOpen(uid:string,wid:string,token:string){const {data,error}=await db.from("journal_positions").select("id").eq("user_id",uid).eq("wallet_id",wid).eq("chain","sol").eq("token_address",token).eq("status","OPEN").limit(1);if(error)throw error;return data?.[0]?.id||null}
async function position(a:any){let id=await findOpen(a.uid,a.wid,a.token);if(!id&&a.dir==="IN"){const {data:manual}=await db.from("journal_positions").select("id,source").eq("user_id",a.uid).eq("chain","sol").eq("status","OPEN").is("wallet_id",null).or(`token_address.eq.${a.token},token_address.is.null`).limit(2);if(manual?.length===1){id=manual[0].id;await db.from("journal_positions").update({wallet_id:a.wid,token_address:a.token,source:manual[0].source==="manual"?"manual+chain":manual[0].source,sync_source:SRC}).eq("id",id)}}
if(!id&&a.dir==="IN"&&a.token!==USDC&&a.token!==WSOL){const sym=`${a.token.slice(0,4)}…${a.token.slice(-4)}`,slug=`sol-${a.token.slice(0,8)}-${a.tx.slice(0,8)}`;const {data,error}=await db.from("journal_positions").insert({user_id:a.uid,wallet_id:a.wid,chain:"sol",token_address:a.token,slug,symbol:sym,short_label:sym.slice(0,2).toUpperCase(),status:"OPEN",opened_label:new Date(a.when).toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"UTC"}),size_label:a.sizeLabel||"Auto-detected",value_label:a.valueLabel||"Solana activity",hold_thesis_required:false,source:"chain-rpc",sync_source:SRC,first_synced_at:iso(),last_synced_at:iso(),last_activity_at:a.when}).select("id").single();if(error)throw error;id=data.id}
if(id){const patch:any={last_activity_at:a.when,last_synced_at:iso(),sync_source:SRC};if(a.sizeLabel)patch.size_label=a.sizeLabel;if(a.valueLabel)patch.value_label=a.valueLabel;await db.from("journal_positions").update(patch).eq("id",id)}return id}
function keyString(k:any){return typeof k==="string"?k:String(k?.pubkey||k?.publicKey||"")}
async function one(w:any){try{const c=await getCursor(w.user_id,w.id),cfg:any={limit:100,commitment:"confirmed"};if(c?.signature)cfg.until=c.signature;const sigs:any[]=await rpc("getSignaturesForAddress",[w.address,cfg]);const newest=sigs?.[0]?.signature||c?.signature||null;let work=(sigs||[]).filter(x=>!x.err);if(!c?.signature){const cut=Math.floor(Date.now()/1000)-300;work=work.filter(x=>(x.blockTime||0)>=cut)}work.reverse();let n=0;
for(const s of work){const tx=await rpc("getTransaction",[s.signature,{encoding:"jsonParsed",commitment:"confirmed",maxSupportedTransactionVersion:0}]);if(!tx?.meta)continue;
const pre=new Map<string,{amount:bigint,decimals:number}>(),post=new Map<string,{amount:bigint,decimals:number}>();
for(const x of tx.meta.preTokenBalances||[])if(x.owner===w.address){const i=tokInfo(x),p=pre.get(x.mint);pre.set(x.mint,{amount:(p?.amount||0n)+i.amount,decimals:i.decimals})}
for(const x of tx.meta.postTokenBalances||[])if(x.owner===w.address){const i=tokInfo(x),p=post.get(x.mint);post.set(x.mint,{amount:(p?.amount||0n)+i.amount,decimals:i.decimals})}
const keys=(tx.transaction?.message?.accountKeys||[]).map(keyString),wi=keys.indexOf(w.address);let nativeSpend="";if(wi>=0){const before=BigInt(tx.meta.preBalances?.[wi]||0),after=BigInt(tx.meta.postBalances?.[wi]||0),fee=BigInt(tx.meta.fee||0);const delta=after-before;if(delta<0n){const spend=(-delta)>fee?(-delta-fee):(-delta);nativeSpend=fmt(spend,9,6)}}
const flows:any[]=[];for(const mint of new Set([...pre.keys(),...post.keys()])){const A=pre.get(mint)||{amount:0n,decimals:post.get(mint)?.decimals||0},B=post.get(mint)||{amount:0n,decimals:A.decimals},delta=B.amount-A.amount;if(delta===0n)continue;flows.push({mint,before:A.amount,after:B.amount,delta,decimals:B.decimals||A.decimals,dir:delta>0n?"IN":"OUT",display:fmt(delta>0n?delta:-delta,B.decimals||A.decimals,6)})}
for(let i=0;i<flows.length;i++){const f=flows[i],when=new Date((tx.blockTime||s.blockTime||Date.now()/1000)*1000).toISOString();const fresh=await recordEvent({uid:w.user_id,wid:w.id,tx:s.signature,idx:`${i}:${f.mint}`,token:f.mint,dir:f.dir,block:String(tx.slot||s.slot||""),when,raw:{mint:f.mint,before:f.before.toString(),after:f.after.toString(),delta:f.delta.toString(),decimals:f.decimals,amount_display:f.display}});if(!fresh)continue;n++;
let sizeLabel="",valueLabel="";if(f.dir==="IN"&&f.mint!==USDC&&f.mint!==WSOL){sizeLabel=`Bought ${f.display} tokens`;let quote:any=null;if(nativeSpend)quote={amount:nativeSpend,symbol:"SOL"};if(!quote){const outs=flows.filter(x=>x.dir==="OUT"&&x.mint!==f.mint);const best=outs.find(x=>x.mint===USDC)||outs.find(x=>x.mint===WSOL)||outs[0];if(best)quote={amount:best.display,symbol:best.mint===USDC?"USDC":best.mint===WSOL?"WSOL":`${best.mint.slice(0,4)}…${best.mint.slice(-4)}`}}if(quote){const r=ratio(quote.amount,f.display);valueLabel=`Spent ${quote.amount} ${quote.symbol}${r?` · entry ${r} ${quote.symbol}/token`:""}`}}
const id=await position({uid:w.user_id,wid:w.id,token:f.mint,dir:f.dir,tx:s.signature,when,sizeLabel,valueLabel});if(id&&f.after===0n)await db.from("journal_positions").update({status:"CLOSED",hold_thesis_required:false,last_synced_at:iso()}).eq("id",id)}
}
await setState(w.user_id,w.id,{cursor:newest?JSON.stringify({signature:newest}):null,status:"OK",last_success_at:iso(),last_attempt_at:iso(),error_code:null,retry_after:null});await db.from("wallets").update({last_sync_status:"OK",last_sync_error:null}).eq("id",w.id);return{ok:true,wallet:w.address,events:n,signatures:work.length}}catch(e){const msg=e instanceof Error?e.message:String(e);await setState(w.user_id,w.id,{status:"ERROR",last_attempt_at:iso(),error_code:msg.slice(0,500)});await db.from("wallets").update({last_sync_status:"ERROR",last_sync_error:msg.slice(0,500)}).eq("id",w.id);return{ok:false,wallet:w.address,error:msg}}}
Deno.serve(async req=>{const {data:rt}=await db.from("sync_runtime").select("sync_key").eq("id",1).single();if(!rt||req.headers.get("x-sync-key")!==rt.sync_key)return response({error:"unauthorized"},401);const body=await req.json().catch(()=>({}));let q=db.from("wallets").select("id,user_id,chain,address,label").eq("sync_enabled",true).eq("chain","sol");if(body.user_id)q=q.eq("user_id",body.user_id);const {data,error}=await q;if(error)return response({error:error.message},500);const results=[];for(const w of data||[])results.push(await one(w));return response({ok:true,source:SRC,results})});